[workspace]
members = [
    "pic"
]

[profile.release]
lto = true
opt-level = 'z'
overflow-checks = true

[profile.bench]
overflow-checks = true

[patch.crates-io]
candid = { git = 'https://github.com/Psychedelic/candid' }
